language: python
python:
- '2.7'
before_install:
- sudo ./init.sh
install:
- pip install -e .[test]
script:
- py.test
deploy:
  provider: pypi
  user: planet
  password:
    secure: moVRXcjStPtmCqW9N0057EY20JhhPAwIh7JbFN8wcx6eYCzN6M8NCErTlEL8fkl5Wx7QreRMHuZo91lf5nDPQfaNieDyRFxRfg/s5oQZePve6etRxxDphSwmlldtRI0Q6osB4muuXsnXx/A72G2PgtgV6f3FdSv3phXMZKEKZfXKU26TYcvjzygK3afXSsv8T4m8LjSnv/nONwYENZYwyZNiT6/gzSQ5TGYpIw0zU4bhMe1ZX54CbRPgzudbe3phV4NpEAbhVWPfZOH0d0iYCjNm/VKPG83Kf2jLT5sD0VzsULfxaxdtPycXjGlPHMzoGFQWH8x8FcnEnTgcD9irATRgQgQQQHDyYjkoAFxymDYglZolWZpswlPK6/D624GzZD19MxWBt2s6UvXDSKupDX/yxNxNwZa3VtXU1/ylfC5IHP9+OMhANKgtw0k4pUNnj1fI5TXQae1EDtLkOxqUfCSIeJr+AZmIFGvqUbQG05G5SGloGv9eGEjoamnUfgU9SM06n0fbVJvXJ5aHwYQ3DUOnfkMLXrKtuRn7qfzTT3hpRbPTQZxM53zMmLfgP7XwzhDT2UE+FaNSXVofFhPq4UP26OycVfYE5y2mt8hAAa/88qmmgrUzakmDJ7lVL/GQx43RynrlaoKAJa+zIChbJP8QWZKR3LFaJZPB9+doKXg=
  on:
    tags: true
    repo: planetlabs/datalake-api
